package com.theblakearnold.stocksolver;

public enum Category {
  TIPS,
  BONDS,
  BONDS_INTL,
  REAL_ESTATE_DOM,
  REAL_ESTATE_INTL,
  EMERGING_MARKETS,
  DOMESTIC_TOTAL,
  DOMESTIC_VALUE,
  DOMESTIC_SMALL_CAP,
  FOREIGN_TOTAL,
  FOREIGN_VALUE,
  FOREIGN_SMALL_CAP;
}
